apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}-set
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "postgres.fullname" . }}-cm
            - secretRef:
                name: {{ include "postgres.fullname" . }}-secret
          volumeMounts:
            - name: linkding-data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" . }}-pvc