apiVersion: v1
entries:
  linkding:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-14T20:30:35.695658904+01:00"
    description: A Helm chart for Kubernetes
    digest: 275d49b1fb78adee917557ab12df2627f7c1858047572a06615a552e2d99ec45
    name: linkding
    type: application
    urls:
    - https://adrian-panek.github.io/linkding-postgres-chart/linkding-0.1.0.tgz
    version: 0.1.0
  postgres:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-14T20:30:35.696723448+01:00"
    description: A Helm chart for Kubernetes
    digest: 8ffe1f9823d34523601753a3b89575edfd331c1564bbefa7ab0d1579a069b6c9
    name: postgres
    type: application
    urls:
    - https://adrian-panek.github.io/linkding-postgres-chart/postgres-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-14T20:30:35.694062099+01:00"
