apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkding.fullname" . }}-secret
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
type: Opaque
stringData:
  LD_SUPERUSER_NAME: {{ .Values.superuser.user }}
  LD_SUPERUSER_PASSWORD: {{ .Values.superuser.password  }}